id = "fantom"
name = "Fantom"
version = "0.0.1"
schema_version = 1
authors = ["Andy Frank <afrankvt@gmail.com>"]
description = "Fantom language support for Zed"
repository = "https://github.com/afrankvt/zed-fantom"

[grammars.fantom]
repository = "https://github.com/afrankvt/zed-fantom"
commit = "383489ee8d73d61e4524082a676fec009f0c65fb"
