id = "fantom"
name = "Fantom"
version = "0.0.1"
schema_version = 1
authors = ["Andy Frank <afrankvt@gmail.com>"]
description = "Fantom language support for Zed"
repository = "https://github.com/afrankvt/zed-fantom"

[grammars.fantom]
repository = "https://github.com/afrankvt/zed-fantom"
commit = "97c78a2f7ad57c7cfe546b32e91caf91fb85b051"
