id = "fantom"
name = "Fantom"
version = "0.0.1"
schema_version = 1
authors = ["Andy Frank <afrankvt@gmail.com>"]
description = "Fantom language support for Zed"
repository = "https://github.com/afrankvt/zed-fantom"

[grammars.fantom]
repository = "https://github.com/afrankvt/zed-fantom"
commit = "e81f4259d891351e46485d56cc33a3268cae90fa"
